### ISSUE TITLE
bug report

### ISSUE THREAD

**Issue by sulincix** [halak0013/pardus_android_emulator#1]
![image](https://github.com/halak0013/pardus_android_emulator/assets/55052890/b97c81f0-62f2-44ad-9857-290bca2238e4)

**Comment by halak0013** [comment]
Thank you for reporting this bug. you can check last commit https://github.com/halak0013/pardus_android_emulator/commit/294936d240eb71df291ba85aab497f016eaa7cce. now it fixied
it become because i try to  fill sdk with a function that give another function. now i added a controller.
